/**
 * app.js - Main Application Logic
 * Kaizen Inventory Management System
 * 
 * Handles UI rendering, navigation, form handling, and all
 * business logic. Depends on supabase.js and pdf.js.
 */

// Ensure global references
var getProductsAPI = () => window.ProductsAPI || (typeof ProductsAPI !== 'undefined' ? ProductsAPI : null);
var getInventoryInAPI = () => window.InventoryInAPI || (typeof InventoryInAPI !== 'undefined' ? InventoryInAPI : null);
var getInventoryOutAPI = () => window.InventoryOutAPI || (typeof InventoryOutAPI !== 'undefined' ? InventoryOutAPI : null);
var getPDFGenerator = () => window.PDFGenerator || (typeof PDFGenerator !== 'undefined' ? PDFGenerator : null);

// ============================================================
// TRANSLATIONS (Arabic & English)
// ============================================================

const translations = {
    en: {
        appName: 'KAIZEN',
        appSubtitle: 'Inventory Management System',
        dashboard: 'Dashboard',
        inventoryIn: 'Inventory In',
        inventoryOut: 'Inventory Out',
        products: 'Products',
        operations: 'Operations History',
        totalProducts: 'Total Products',
        totalQuantity: 'Total Inventory Quantity',
        totalValue: 'Total Inventory Value',
        totalInOps: 'Total Inventory In Operations',
        totalOutOps: 'Total Inventory Out Operations',
        inventoryInAction: 'Inventory In',
        inventoryOutAction: 'Inventory Out',
        recentOperations: 'Recent Operations',
        newInventoryIn: 'New Inventory In',
        newInventoryOut: 'New Inventory Out',
        productName: 'Product Name',
        quantity: 'Quantity',
        unitPrice: 'Unit Price',
        totalPrice: 'Total Price',
        supplierName: 'Supplier Name',
        entryDate: 'Entry Date',
        employeeName: 'Employee Name',
        notes: 'Notes (Optional)',
        submit: 'Submit',
        cancel: 'Cancel',
        reset: 'Reset',
        totalSellingPrice: 'Total Selling Price',
        customerName: 'Customer Name',
        date: 'Date',
        employeeSellerName: 'Employee / Seller Name',
        currentQuantity: 'Current Quantity',
        stockValue: 'Stock Value',
        lastUpdated: 'Last Updated',
        search: 'Search...',
        filterByDate: 'Filter by date',
        filterByEmployee: 'Filter by employee',
        filterByProduct: 'Filter by product',
        all: 'All',
        type: 'Type',
        downloadPDF: 'Download PDF',
        noData: 'No data available',
        noProducts: 'No products in inventory',
        noOperations: 'No operations recorded',
        success: 'Success',
        error: 'Error',
        recordAdded: 'Record added successfully!',
        recordError: 'Error adding record. Please try again.',
        insufficientStock: 'Insufficient stock! Available:',
        selectProduct: 'Select a product...',
        loading: 'Loading...',
        generatedByKaizen: 'Generated by Kaizen Inventory Management System',
        generatedOn: 'Generated on',
        inventoryInReceipt: 'INVENTORY IN - RECEIPT',
        inventoryOutReceipt: 'INVENTORY OUT - ISSUE SLIP',
        transactionDetails: 'Transaction Details',
        receiptNo: 'Receipt No',
        issueNo: 'Issue No',
        issueDate: 'Issue Date',
        inventoryManagementSystem: 'Inventory Management System',
        stock: 'Stock',
        in: 'In',
        out: 'Out',
        autoCalculated: 'Auto-calculated',
        viewAll: 'View All',
        currencySymbol: 'EGP',
        actions: 'Actions',
        editQuantity: 'Edit Quantity',
        selectEmployee: 'Select Employee...',
        newQuantity: 'New Quantity',
        save: 'Save',
        empMai: 'Mai',
        empSuhaila: 'Suhaila',
        empRahma: 'Rahma',
        deleteProductTitle: 'Delete Product',
        confirmDeleteMsg: 'Are you sure you want to delete this product?',
        deleteBtn: 'Delete',
        editProductTitle: 'Edit Product Details',
        editProductBtn: 'Edit',
        productImage: 'Product Image',
        imageUrlPlaceholder: 'Or paste image link/URL here...',
        imageHint: 'You can upload a photo from your device or paste an image link.',
        productCode: 'Product Code / Barcode (SKU)',
        addCodeBtn: '⚡ Generate Code',
        codePlaceholder: 'Type, scan or generate SKU code...'
    },
    ar: {
        appName: 'كايزن',
        appSubtitle: 'نظام إدارة المخزون',
        dashboard: 'لوحة التحكم',
        inventoryIn: 'إدخال مخزون',
        inventoryOut: 'إخراج مخزون',
        products: 'المنتجات',
        operations: 'سجل العمليات',
        totalProducts: 'إجمالي المنتجات',
        totalQuantity: 'إجمالي كمية المخزون',
        totalValue: 'إجمالي قيمة المخزون',
        totalInOps: 'إجمالي عمليات الإدخال',
        totalOutOps: 'إجمالي عمليات الإخراج',
        inventoryInAction: 'إدخال مخزون',
        inventoryOutAction: 'إخراج مخزون',
        recentOperations: 'آخر العمليات',
        newInventoryIn: 'عملية إدخال جديدة',
        newInventoryOut: 'عملية إخراج جديدة',
        productName: 'اسم المنتج',
        quantity: 'الكمية',
        unitPrice: 'سعر الوحدة',
        totalPrice: 'السعر الإجمالي',
        supplierName: 'اسم المورد',
        entryDate: 'تاريخ الإدخال',
        employeeName: 'اسم الموظف',
        notes: 'ملاحظات (اختياري)',
        submit: 'إرسال',
        cancel: 'إلغاء',
        reset: 'إعادة تعيين',
        totalSellingPrice: 'سعر البيع الإجمالي',
        customerName: 'اسم العميل',
        date: 'التاريخ',
        employeeSellerName: 'اسم الموظف / البائع',
        currentQuantity: 'الكمية الحالية',
        stockValue: 'قيمة المخزون',
        lastUpdated: 'آخر تحديث',
        search: 'بحث...',
        filterByDate: 'تصفية حسب التاريخ',
        filterByEmployee: 'تصفية حسب الموظف',
        filterByProduct: 'تصفية حسب المنتج',
        all: 'الكل',
        type: 'النوع',
        downloadPDF: 'تحميل PDF',
        noData: 'لا توجد بيانات',
        noProducts: 'لا توجد منتجات في المخزون',
        noOperations: 'لا توجد عمليات مسجلة',
        success: 'تم بنجاح',
        error: 'خطأ',
        recordAdded: 'تمت إضافة السجل بنجاح!',
        recordError: 'خطأ في إضافة السجل. يرجى المحاولة مرة أخرى.',
        insufficientStock: 'مخزون غير كاف! المتاح:',
        selectProduct: 'اختر منتج...',
        loading: 'جاري التحميل...',
        generatedByKaizen: 'تم إنشاؤه بواسطة نظام كايزن لإدارة المخزون',
        generatedOn: 'تاريخ الإنشاء',
        inventoryInReceipt: 'إيصال إدخال مخزون',
        inventoryOutReceipt: 'إيصال إخراج مخزون',
        transactionDetails: 'تفاصيل العملية',
        receiptNo: 'رقم الإيصال',
        issueNo: 'رقم الصرف',
        issueDate: 'تاريخ الصرف',
        inventoryManagementSystem: 'نظام إدارة المخزون',
        stock: 'المخزون',
        in: 'داخل',
        out: 'خارج',
        autoCalculated: 'تحسب تلقائيا',
        viewAll: 'عرض الكل',
        currencySymbol: 'ج.م',
        actions: 'إجراءات',
        editQuantity: 'تعديل الكمية',
        selectEmployee: 'اختر الموظف...',
        newQuantity: 'الكمية الجديدة',
        save: 'حفظ',
        empMai: 'مي',
        empSuhaila: 'سهيلة',
        empRahma: 'رحمة',
        deleteProductTitle: 'حذف المنتج',
        confirmDeleteMsg: 'هل أنت متأكد من حذف هذا المنتج؟',
        deleteBtn: 'حذف',
        editProductTitle: 'تعديل بيانات المنتج',
        editProductBtn: 'تعديل',
        productImage: 'صورة المنتج',
        imageUrlPlaceholder: 'أو ضع رابط الصورة على الإنترنت هنا...',
        imageHint: 'يمكنك اختيار أو التقاط صورة من جهازك، أو وضع رابط صورة مباشر.',
        productCode: 'كود المنتج / الباركود (SKU)',
        addCodeBtn: '⚡ توليد كود تلقائي',
        codePlaceholder: 'اكتب أو امسح الباركود، أو اضغط توليد...'
    }
};

// ============================================================
// APPLICATION STATE & EMPLOYEES
// ============================================================

const AppState = {
    currentPage: 'dashboard',
    currentLang: 'en',
    products: [],
    inventoryIn: [],
    inventoryOut: []
};

const EMPLOYEES = [
    { ar: 'مي', en: 'empMai' },
    { ar: 'سهيلة', en: 'empSuhaila' },
    { ar: 'رحمة', en: 'empRahma' }
];

function getEmployeeOptions(selected = '') {
    const defaultOption = `<option value="">${t('selectEmployee')}</option>`;
    return defaultOption + EMPLOYEES.map(emp => {
        const label = t(emp.en) || emp.ar;
        const isSelected = emp.ar === selected || label === selected ? 'selected' : '';
        return `<option value="${emp.ar}" ${isSelected}>${label}</option>`;
    }).join('');
}

// ============================================================
// UTILITY FUNCTIONS
// ============================================================

function t(key) {
    return translations[AppState.currentLang][key] || key;
}

function formatCurrency(amount) {
    const num = parseFloat(amount) || 0;
    const symbol = t('currencySymbol') || 'ج.م';
    const formatted = new Intl.NumberFormat(AppState.currentLang === 'ar' ? 'ar-EG' : 'en-US', {
        minimumFractionDigits: 2,
        maximumFractionDigits: 2
    }).format(num);
    return `${formatted} ${symbol}`;
}

function formatNumber(num) {
    return new Intl.NumberFormat(AppState.currentLang === 'ar' ? 'ar-SA' : 'en-US').format(parseFloat(num) || 0);
}

function formatDate(dateStr) {
    if (!dateStr) return '-';
    return new Date(dateStr).toLocaleDateString(AppState.currentLang === 'ar' ? 'ar-SA' : 'en-US', {
        year: 'numeric', month: 'short', day: 'numeric'
    });
}

function escapeHtml(str) {
    if (!str) return '';
    const div = document.createElement('div');
    div.textContent = str;
    return div.innerHTML;
}

function showToast(message, type = 'success') {
    const container = document.getElementById('toastContainer');
    const toast = document.createElement('div');
    toast.className = `toast toast-${type}`;
    const icons = { success: '✓', error: '✕', warning: '⚠', info: 'ℹ' };
    toast.innerHTML = `<span>${icons[type] || ''}</span> ${message}`;
    container.appendChild(toast);
    setTimeout(() => {
        toast.style.opacity = '0';
        toast.style.transition = 'opacity 0.3s ease';
        setTimeout(() => toast.remove(), 300);
    }, 3500);
}

function showLoading() {
    document.getElementById('loadingOverlay').classList.add('active');
}

function hideLoading() {
    document.getElementById('loadingOverlay').classList.remove('active');
}

function getTodayDate() {
    return new Date().toISOString().split('T')[0];
}

// ============================================================
// NAVIGATION
// ============================================================

function navigateTo(page) {
    AppState.currentPage = page;
    document.querySelectorAll('.sidebar-nav a').forEach(link => {
        link.classList.toggle('active', link.dataset.page === page);
    });
    renderPage(page);
    closeSidebar();
    const titles = {
        dashboard: t('dashboard'),
        'inventory-in': t('inventoryIn'),
        'inventory-out': t('inventoryOut'),
        products: t('products'),
        operations: t('operations')
    };
    document.getElementById('pageTitle').textContent = titles[page] || 'Kaizen';
}

function renderPage(page) {
    const content = document.getElementById('contentArea');
    switch (page) {
        case 'dashboard':
            content.innerHTML = renderDashboard();
            loadDashboardData();
            break;
        case 'inventory-in':
            content.innerHTML = renderInventoryInForm();
            initInventoryInForm();
            break;
        case 'inventory-out':
            content.innerHTML = renderInventoryOutForm();
            initInventoryOutForm();
            break;
        case 'products':
            content.innerHTML = renderProductsPage();
            loadProductsData();
            break;
        case 'operations':
            content.innerHTML = renderOperationsPage();
            loadOperationsData();
            break;
        default:
            content.innerHTML = renderDashboard();
            loadDashboardData();
    }
}

function toggleSidebar() {
    document.getElementById('sidebar').classList.toggle('open');
    document.getElementById('sidebarOverlay').classList.toggle('active');
}

function closeSidebar() {
    document.getElementById('sidebar').classList.remove('open');
    document.getElementById('sidebarOverlay').classList.remove('active');
}

// ============================================================
// LANGUAGE SWITCHING
// ============================================================

function switchLanguage(lang) {
    AppState.currentLang = lang;
    document.body.dir = lang === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = lang;
    document.querySelectorAll('.lang-btn').forEach(btn => {
        btn.classList.toggle('active', btn.dataset.lang === lang);
    });
    renderPage(AppState.currentPage);
    localStorage.setItem('kaizen_lang', lang);
}

// ============================================================
// DASHBOARD
// ============================================================

function renderDashboard() {
    return `
        <div class="stats-grid">
            <div class="stat-card card-products">
                <div class="stat-icon" style="background:#dbeafe;color:#1e3a8a;">📦</div>
                <div class="stat-value" id="statProducts">-</div>
                <div class="stat-label">${t('totalProducts')}</div>
            </div>
            <div class="stat-card card-quantity">
                <div class="stat-icon" style="background:#dcfce7;color:#16a34a;">📊</div>
                <div class="stat-value" id="statQuantity">-</div>
                <div class="stat-label">${t('totalQuantity')}</div>
            </div>
            <div class="stat-card card-value">
                <div class="stat-icon" style="background:#fef3c7;color:#f59e0b;">💰</div>
                <div class="stat-value" id="statValue">-</div>
                <div class="stat-label">${t('totalValue')}</div>
            </div>
            <div class="stat-card card-in">
                <div class="stat-icon" style="background:#cffafe;color:#06b6d4;">📥</div>
                <div class="stat-value" id="statInOps">-</div>
                <div class="stat-label">${t('totalInOps')}</div>
            </div>
            <div class="stat-card card-out">
                <div class="stat-icon" style="background:#fee2e2;color:#dc2626;">📤</div>
                <div class="stat-value" id="statOutOps">-</div>
                <div class="stat-label">${t('totalOutOps')}</div>
            </div>
        </div>
        <div class="action-buttons">
            <button class="btn-action btn-in" onclick="navigateTo('inventory-in')">
                <span class="action-icon">📥</span>
                <span>${t('inventoryInAction')}</span>
                <span style="font-size:0.8rem;opacity:0.7;">${t('newInventoryIn')}</span>
            </button>
            <button class="btn-action btn-out" onclick="navigateTo('inventory-out')">
                <span class="action-icon">📤</span>
                <span>${t('inventoryOutAction')}</span>
                <span style="font-size:0.8rem;opacity:0.7;">${t('newInventoryOut')}</span>
            </button>
        </div>
        <div class="table-container">
            <div class="table-header">
                <h3 class="table-title">${t('recentOperations')}</h3>
                <button class="btn btn-outline btn-sm" onclick="navigateTo('operations')">${t('viewAll')} →</button>
            </div>
            <div class="table-wrap">
                <table>
                    <thead>
                        <tr>
                            <th>${t('type')}</th>
                            <th>${t('productName')}</th>
                            <th>${t('quantity')}</th>
                            <th>${t('date')}</th>
                            <th>${t('employeeName')}</th>
                        </tr>
                    </thead>
                    <tbody id="recentOperationsBody">
                        <tr><td colspan="5" class="empty-state"><p>${t('loading')}</p></td></tr>
                    </tbody>
                </table>
            </div>
        </div>
    `;
}

async function loadDashboardData() {
    try {
        showLoading();
        const [products, inRecords, outRecords] = await Promise.all([
            getProductsAPI() ? getProductsAPI().getAll() : [],
            getInventoryInAPI() ? getInventoryInAPI().getAll() : [],
            getInventoryOutAPI() ? getInventoryOutAPI().getAll() : []
        ]);
        AppState.products = products;
        AppState.inventoryIn = inRecords;
        AppState.inventoryOut = outRecords;

        const totalProducts = products.length;
        const totalQuantity = products.reduce((s, p) => s + parseFloat(p.quantity || 0), 0);
        const totalValue = products.reduce((s, p) => s + (parseFloat(p.quantity || 0) * parseFloat(p.unit_price || 0)), 0);

        document.getElementById('statProducts').textContent = formatNumber(totalProducts);
        document.getElementById('statQuantity').textContent = formatNumber(totalQuantity);
        document.getElementById('statValue').textContent = formatCurrency(totalValue);
        document.getElementById('statInOps').textContent = formatNumber(inRecords.length);
        document.getElementById('statOutOps').textContent = formatNumber(outRecords.length);

        const allOps = [
            ...inRecords.map(r => ({ ...r, opType: 'in', dateField: r.entry_date || r.created_at })),
            ...outRecords.map(r => ({ ...r, opType: 'out', dateField: r.date || r.created_at }))
        ].sort((a, b) => new Date(b.created_at) - new Date(a.created_at)).slice(0, 10);

        const tbody = document.getElementById('recentOperationsBody');
        if (allOps.length === 0) {
            tbody.innerHTML = `<tr><td colspan="5" class="empty-state"><p>${t('noOperations')}</p></td></tr>`;
        } else {
            tbody.innerHTML = allOps.map(op => `
                <tr>
                    <td><span class="badge ${op.opType === 'in' ? 'badge-in' : 'badge-out'}">${op.opType === 'in' ? '📥 ' + t('in') : '📤 ' + t('out')}</span></td>
                    <td>${escapeHtml(op.product_name)}</td>
                    <td>${formatNumber(op.quantity)}</td>
                    <td>${formatDate(op.dateField)}</td>
                    <td>${escapeHtml(op.employee_name || '-')}</td>
                </tr>
            `).join('');
        }
    } catch (err) {
        // Silent fail
    } finally {
        hideLoading();
    }
}

// ============================================================
// INVENTORY IN FORM
// ============================================================

function renderInventoryInForm() {
    return `
        <div class="form-card">
            <h2 class="form-card-title">📥 ${t('newInventoryIn')}</h2>
            <form id="inventoryInForm" onsubmit="handleInventoryInSubmit(event)">
                <div class="form-grid">
                    <div class="form-group">
                        <label class="form-label">${t('productName')} <span class="required">*</span></label>
                        <input type="text" class="form-input" id="inProductName" required placeholder="${t('productName')}" list="productSuggestions">
                        <datalist id="productSuggestions"></datalist>
                    </div>
                    <div class="form-group">
                        <label class="form-label">${t('quantity')} <span class="required">*</span></label>
                        <input type="number" class="form-input" id="inQuantity" required min="0.01" step="0.01" placeholder="0" oninput="calcInTotalPrice()">
                    </div>
                    <div class="form-group">
                        <label class="form-label">${t('unitPrice')}</label>
                        <input type="number" class="form-input" id="inUnitPrice" min="0" step="0.01" placeholder="0.00" oninput="calcInTotalPrice()">
                    </div>
                    <div class="form-group">
                        <label class="form-label">${t('totalPrice')}</label>
                        <input type="number" class="form-input calculated" id="inTotalPrice" min="0" step="0.01" placeholder="0.00" oninput="calcInUnitPrice()">
                        <span class="form-hint">${t('autoCalculated')}</span>
                    </div>
                    <div class="form-group">
                        <label class="form-label">${t('supplierName')}</label>
                        <input type="text" class="form-input" id="inSupplierName" placeholder="${t('supplierName')}">
                    </div>
                    <div class="form-group">
                        <label class="form-label">${t('entryDate')}</label>
                        <input type="date" class="form-input" id="inEntryDate" value="${getTodayDate()}">
                    </div>
                    <div class="form-group">
                        <label class="form-label">${t('employeeName')}</label>
                        <select class="form-select" id="inEmployeeName">
                            ${getEmployeeOptions()}
                        </select>
                    </div>
                    <div class="form-group full-width">
                        <label class="form-label">${t('notes')}</label>
                        <textarea class="form-textarea" id="inNotes" placeholder="${t('notes')}"></textarea>
                    </div>
                </div>
                <div class="btn-group">
                    <button type="submit" class="btn btn-success btn-lg">✓ ${t('submit')}</button>
                    <button type="reset" class="btn btn-outline btn-lg">↺ ${t('reset')}</button>
                </div>
            </form>
        </div>
    `;
}

async function initInventoryInForm() {
    if (AppState.products.length === 0 && getProductsAPI()) {
        try { AppState.products = await getProductsAPI().getAll(); } catch (e) { /* silent */ }
    }
    updateProductSuggestions();
}

function calcInTotalPrice() {
    const q = parseFloat(document.getElementById('inQuantity').value) || 0;
    const u = parseFloat(document.getElementById('inUnitPrice').value) || 0;
    if (q > 0 && u > 0) document.getElementById('inTotalPrice').value = (q * u).toFixed(2);
}

function calcInUnitPrice() {
    const q = parseFloat(document.getElementById('inQuantity').value) || 0;
    const tp = parseFloat(document.getElementById('inTotalPrice').value) || 0;
    if (q > 0 && tp > 0) document.getElementById('inUnitPrice').value = (tp / q).toFixed(2);
}

async function handleInventoryInSubmit(event) {
    event.preventDefault();
    try {
        showLoading();
        const q = parseFloat(document.getElementById('inQuantity').value) || 0;
        const u = parseFloat(document.getElementById('inUnitPrice').value) || 0;
        let tp = parseFloat(document.getElementById('inTotalPrice').value);
        if (isNaN(tp) || !tp) tp = q * u;

        const record = {
            product_name: document.getElementById('inProductName').value.trim(),
            quantity: q,
            unit_price: u,
            total_price: tp,
            supplier_name: document.getElementById('inSupplierName').value.trim(),
            entry_date: document.getElementById('inEntryDate').value || getTodayDate(),
            employee_name: document.getElementById('inEmployeeName').value.trim(),
            notes: document.getElementById('inNotes').value.trim()
        };
        if (!record.product_name || isNaN(record.quantity) || record.quantity <= 0) {
            hideLoading(); return;
        }
        if (getProductsAPI()) await getProductsAPI().updateQuantity(record.product_name, record.quantity, record.unit_price, record.supplier_name);
        if (getInventoryInAPI()) await getInventoryInAPI().add(record);
        showToast(t('recordAdded'), 'success');
        document.getElementById('inventoryInForm').reset();
        document.getElementById('inEntryDate').value = getTodayDate();
        if (getProductsAPI()) AppState.products = await getProductsAPI().getAll();
        updateProductSuggestions();
    } catch (err) {
        // Silent fail
    } finally {
        hideLoading();
    }
}

function updateProductSuggestions() {
    const datalist = document.getElementById('productSuggestions');
    if (!datalist) return;
    datalist.innerHTML = AppState.products.map(p =>
        `<option value="${escapeHtml(p.name)}">${escapeHtml(p.name)} (${t('stock')}: ${formatNumber(p.quantity)})</option>`
    ).join('');
}

// ============================================================
// INVENTORY OUT FORM
// ============================================================

function renderInventoryOutForm() {
    return `
        <div class="form-card">
            <h2 class="form-card-title">📤 ${t('newInventoryOut')}</h2>
            <form id="inventoryOutForm" onsubmit="handleInventoryOutSubmit(event)">
                <div class="form-grid">
                    <div class="form-group">
                        <label class="form-label">${t('productName')} <span class="required">*</span></label>
                        <select class="form-select" id="outProductName" required onchange="onOutProductChange()">
                            <option value="">${t('selectProduct')}</option>
                        </select>
                        <span class="form-hint" id="outStockInfo"></span>
                    </div>
                    <div class="form-group">
                        <label class="form-label">${t('quantity')} <span class="required">*</span></label>
                        <input type="number" class="form-input" id="outQuantity" required min="0.01" step="0.01" placeholder="0" oninput="validateOutQuantity()">
                        <span class="form-hint" id="outQuantityHint"></span>
                    </div>
                    <div class="form-group">
                        <label class="form-label">${t('totalSellingPrice')} <span class="required">*</span></label>
                        <input type="number" class="form-input" id="outTotalPrice" required min="0.01" step="0.01" placeholder="0.00">
                    </div>
                    <div class="form-group">
                        <label class="form-label">${t('customerName')}</label>
                        <input type="text" class="form-input" id="outCustomerName" placeholder="${t('customerName')}">
                    </div>
                    <div class="form-group">
                        <label class="form-label">${t('date')} <span class="required">*</span></label>
                        <input type="date" class="form-input" id="outDate" required value="${getTodayDate()}">
                    </div>
                    <div class="form-group">
                        <label class="form-label">${t('employeeSellerName')} <span class="required">*</span></label>
                        <select class="form-select" id="outEmployeeName" required>
                            ${getEmployeeOptions()}
                        </select>
                    </div>
                    <div class="form-group full-width">
                        <label class="form-label">${t('notes')}</label>
                        <textarea class="form-textarea" id="outNotes" placeholder="${t('notes')}"></textarea>
                    </div>
                </div>
                <div class="btn-group">
                    <button type="submit" class="btn btn-danger btn-lg">✓ ${t('submit')}</button>
                    <button type="reset" class="btn btn-outline btn-lg">↺ ${t('reset')}</button>
                </div>
            </form>
        </div>
    `;
}

async function initInventoryOutForm() {
    await loadProductsForSelect();
}

async function loadProductsForSelect() {
    try {
        const products = getProductsAPI() ? await getProductsAPI().getAll() : [];
        AppState.products = products;
        const select = document.getElementById('outProductName');
        if (!select) return;
        select.innerHTML = `<option value="">${t('selectProduct')}</option>`;
        products.forEach(p => {
            const option = document.createElement('option');
            option.value = p.name;
            option.textContent = `${p.name} (${t('stock')}: ${formatNumber(p.quantity)})`;
            option.dataset.quantity = p.quantity;
            select.appendChild(option);
        });
    } catch (err) { /* silent */ }
}

function onOutProductChange() {
    const select = document.getElementById('outProductName');
    const selectedOption = select.selectedOptions[0];
    const stockInfo = document.getElementById('outStockInfo');
    if (selectedOption && selectedOption.dataset.quantity) {
        const qty = parseFloat(selectedOption.dataset.quantity);
        stockInfo.textContent = `${t('currentQuantity')}: ${formatNumber(qty)}`;
        document.getElementById('outQuantity').max = qty;
        document.getElementById('outQuantityHint').textContent = `${t('stock')}: ${formatNumber(qty)}`;
    } else {
        stockInfo.textContent = '';
        document.getElementById('outQuantityHint').textContent = '';
    }
}

function validateOutQuantity() {
    const select = document.getElementById('outProductName');
    const selectedOption = select.selectedOptions[0];
    const qtyInput = document.getElementById('outQuantity');
    const hint = document.getElementById('outQuantityHint');
    if (selectedOption && selectedOption.dataset.quantity) {
        const available = parseFloat(selectedOption.dataset.quantity);
        const requested = parseFloat(qtyInput.value) || 0;
        if (requested > available) {
            hint.style.color = '#dc2626';
            hint.textContent = `⚠ ${t('insufficientStock')} ${formatNumber(available)}`;
        } else {
            hint.style.color = '';
            hint.textContent = `${t('stock')}: ${formatNumber(available)}`;
        }
    }
}

async function handleInventoryOutSubmit(event) {
    event.preventDefault();
    try {
        showLoading();
        const select = document.getElementById('outProductName');
        const selectedOption = select?.selectedOptions?.[0];
        const availableQty = selectedOption ? parseFloat(selectedOption.dataset.quantity || 0) : 0;
        const requestedQty = parseFloat(document.getElementById('outQuantity').value) || 0;

        if (requestedQty > availableQty || requestedQty <= 0) {
            hideLoading(); return;
        }

        const record = {
            product_name: document.getElementById('outProductName').value,
            quantity: requestedQty,
            total_selling_price: parseFloat(document.getElementById('outTotalPrice').value) || 0,
            customer_name: document.getElementById('outCustomerName').value.trim(),
            date: document.getElementById('outDate').value || getTodayDate(),
            employee_name: document.getElementById('outEmployeeName').value.trim(),
            notes: document.getElementById('outNotes').value.trim()
        };

        if (!record.product_name || !record.quantity) {
            hideLoading(); return;
        }

        if (getProductsAPI()) await getProductsAPI().updateQuantity(record.product_name, -record.quantity);
        if (getInventoryOutAPI()) await getInventoryOutAPI().add(record);
        showToast(t('recordAdded'), 'success');
        document.getElementById('inventoryOutForm').reset();
        document.getElementById('outDate').value = getTodayDate();
        const stockInfo = document.getElementById('outStockInfo');
        if (stockInfo) stockInfo.textContent = '';
        const qtyHint = document.getElementById('outQuantityHint');
        if (qtyHint) qtyHint.textContent = '';
        if (getProductsAPI()) AppState.products = await getProductsAPI().getAll();
        await loadProductsForSelect();
    } catch (err) {
        // Silent fail
    } finally {
        hideLoading();
    }
}

// ============================================================
// PRODUCTS PAGE
// ============================================================

function renderProductsPage() {
    return `
        <div class="table-container">
            <div class="table-header">
                <h3 class="table-title">📦 ${t('products')}</h3>
                <div class="table-filters">
                    <input type="text" class="form-input" id="productSearch" placeholder="${t('search')}" oninput="filterProductsTable()">
                </div>
            </div>
            <div class="table-wrap">
                <table>
                    <thead>
                        <tr>
                            <th>${t('productName')}</th>
                            <th>${t('currentQuantity')}</th>
                            <th>${t('unitPrice')}</th>
                            <th>${t('stockValue')}</th>
                            <th>${t('supplierName')}</th>
                            <th>${t('lastUpdated')}</th>
                            <th>${t('actions')}</th>
                        </tr>
                    </thead>
                    <tbody id="productsTableBody">
                        <tr><td colspan="7" class="empty-state"><p>${t('loading')}</p></td></tr>
                    </tbody>
                </table>
            </div>
        </div>
    `;
}

async function loadProductsData() {
    try {
        showLoading();
        AppState.products = getProductsAPI() ? await getProductsAPI().getAll() : [];
        renderProductsTable(AppState.products);
    } catch (err) {
        // Silent fail
    } finally {
        hideLoading();
    }
}

function renderProductsTable(products) {
    const tbody = document.getElementById('productsTableBody');
    if (!tbody) return;
    if (products.length === 0) {
        tbody.innerHTML = `<tr><td colspan="7" class="empty-state"><div class="empty-icon">📦</div><p>${t('noProducts')}</p></td></tr>`;
        return;
    }
    tbody.innerHTML = products.map(p => {
        const code = p.product_code || (window.KaizenCodes && window.KaizenCodes.get(p.name)) || '';
        return `
        <tr>
            <td>
                <div style="display:flex;align-items:center;gap:0.75rem;">
                    <div style="width:40px;height:40px;border-radius:8px;background:#f8fafc;display:flex;align-items:center;justify-content:center;overflow:hidden;flex-shrink:0;border:1px solid var(--border);font-size:1.25rem;">
                        ${(p.image_url || (window.KaizenImages && window.KaizenImages.get(p.name))) ? `<img src="${p.image_url || window.KaizenImages.get(p.name)}" style="width:100%;height:100%;object-fit:cover;" onerror="this.parentElement.innerHTML='📦'"/>` : '📦'}
                    </div>
                    <div style="display:flex;flex-direction:column;">
                        <strong>${escapeHtml(p.name)}</strong>
                        ${code ? `<span style="font-size:0.75rem;color:var(--primary);font-family:monospace;background:#eff6ff;padding:0.1rem 0.4rem;border-radius:4px;width:fit-content;margin-top:0.15rem;border:1px solid #bfdbfe;">🔖 ${escapeHtml(code)}</span>` : ''}
                    </div>
                </div>
            </td>
            <td>${formatNumber(p.quantity)}</td>
            <td>${formatCurrency(p.unit_price)}</td>
            <td><strong>${formatCurrency(parseFloat(p.quantity || 0) * parseFloat(p.unit_price || 0))}</strong></td>
            <td>${escapeHtml(p.supplier_name || '-')}</td>
            <td>${formatDate(p.updated_at)}</td>
            <td>
                <div style="display:flex;gap:0.4rem;align-items:center;">
                    <button class="btn btn-sm btn-outline" onclick="openEditModal('${escapeHtml(p.name).replace(/'/g, "\\'")}', '${p.quantity || 0}', '${p.unit_price || 0}', '${escapeHtml(p.supplier_name || '').replace(/'/g, "\\'")}', '${p.id || ''}')" title="${t('editProductBtn')}">
                        ✏️
                    </button>
                    <button class="btn btn-sm btn-outline" style="color:var(--danger);border-color:var(--danger);" onclick="openDeleteModal('${escapeHtml(p.name).replace(/'/g, "\\'")}', '${p.id || ''}')" title="${t('deleteBtn')}">
                        🗑️
                    </button>
                </div>
            </td>
        </tr>
    `}).join('');
}

function filterProductsTable() {
    const query = (document.getElementById('productSearch')?.value || '').toLowerCase();
    const filtered = AppState.products.filter(p => {
        const code = p.product_code || (window.KaizenCodes && window.KaizenCodes.get(p.name)) || '';
        return p.name.toLowerCase().includes(query) ||
               (p.supplier_name && p.supplier_name.toLowerCase().includes(query)) ||
               code.toLowerCase().includes(query);
    });
    renderProductsTable(filtered);
}

function openEditModal(name, currentQty, currentPrice, currentSupplier, id) {
    const box = document.getElementById('customModalBox');
    const overlay = document.getElementById('customModalOverlay');
    if (!box || !overlay) return;
    const prod = AppState.products.find(x => x.name === name || (id && x.id === id));
    const currentImg = (window.KaizenImages && window.KaizenImages.get(name)) || prod?.image_url || '';
    const currentCode = (window.KaizenCodes && window.KaizenCodes.get(name)) || prod?.product_code || '';

    box.innerHTML = `
        <h3 class="modal-title">✏️ ${t('editProductTitle')}: ${escapeHtml(name)}</h3>
        <form onsubmit="submitEditProduct(event, '${escapeHtml(name).replace(/'/g, "\\'")}', '${id || ''}')" style="margin-top:1rem;">
            <div class="form-group" style="margin-bottom:1rem;">
                <label class="form-label">${t('productImage')}</label>
                <div style="display:flex;align-items:center;gap:1rem;margin-top:0.35rem;">
                    <div id="editImagePreview" style="width:64px;height:64px;border-radius:8px;background:#f8fafc;border:1.5px dashed var(--border);display:flex;align-items:center;justify-content:center;overflow:hidden;flex-shrink:0;font-size:1.8rem;">
                        ${currentImg ? `<img src="${currentImg}" style="width:100%;height:100%;object-fit:cover;" onerror="this.parentElement.innerHTML='📦'"/>` : '📦'}
                    </div>
                    <div style="flex:1;display:flex;flex-direction:column;gap:0.45rem;">
                        <input type="file" id="editImageFile" accept="image/*" class="form-input" style="padding:0.35rem;font-size:0.8rem;" onchange="previewSelectedImage(event)">
                        <input type="url" id="editImageUrl" class="form-input" style="padding:0.45rem;font-size:0.825rem;" placeholder="${t('imageUrlPlaceholder')}" value="${currentImg.startsWith('data:') ? '' : escapeHtml(currentImg)}" oninput="previewUrlImage(event)">
                        <input type="hidden" id="editImageBase64" value="${escapeHtml(currentImg)}">
                    </div>
                </div>
                <span class="form-hint" style="margin-top:0.25rem;">${t('imageHint')}</span>
            </div>
            <div class="form-group" style="margin-bottom:0.8rem;">
                <label class="form-label">${t('productCode')}</label>
                <div style="display:flex;gap:0.5rem;align-items:center;">
                    <input type="text" id="editCodeInput" class="form-input" style="flex:1;font-family:monospace;font-weight:bold;letter-spacing:1px;" placeholder="${t('codePlaceholder')}" value="${escapeHtml(currentCode)}">
                    <button type="button" class="btn btn-outline btn-sm" onclick="generateAutoCode()" style="flex-shrink:0;">${t('addCodeBtn')}</button>
                </div>
            </div>
            <div class="form-group" style="margin-bottom:0.8rem;">
                <label class="form-label">${t('productName')}</label>
                <input type="text" class="form-input" id="editNameInput" value="${escapeHtml(name)}" required autofocus>
            </div>
            <div class="form-group" style="margin-bottom:0.8rem;">
                <label class="form-label">${t('quantity')}</label>
                <input type="number" class="form-input" id="editQtyInput" value="${currentQty}" min="0" step="0.01" required>
            </div>
            <div class="form-group" style="margin-bottom:0.8rem;">
                <label class="form-label">${t('unitPrice')}</label>
                <input type="number" class="form-input" id="editPriceInput" value="${currentPrice || 0}" min="0" step="0.01" required>
            </div>
            <div class="form-group" style="margin-bottom:1.25rem;">
                <label class="form-label">${t('supplierName')}</label>
                <input type="text" class="form-input" id="editSupplierInput" value="${escapeHtml(currentSupplier || '')}" placeholder="${t('supplierName')}">
            </div>
            <div class="modal-actions">
                <button type="button" class="btn btn-outline" onclick="closeCustomModal()">${t('cancel')}</button>
                <button type="submit" class="btn btn-primary">✓ ${t('save')}</button>
            </div>
        </form>
    `;
    overlay.classList.add('active');
}

function generateAutoCode() {
    const input = document.getElementById('editCodeInput');
    if (!input) return;
    const prefix = 'KZ-';
    const randDigits = Math.floor(100000 + Math.random() * 900000);
    input.value = prefix + randDigits;
    if (window.showToast) window.showToast('⚡ ' + (AppState.currentLang === 'ar' ? 'تم توليد الكود التلقائي بنجاح!' : 'Code generated successfully!'), 'info');
}

function previewSelectedImage(event) {
    const file = event.target.files?.[0];
    if (!file) return;
    const reader = new FileReader();
    reader.onload = function(e) {
        const img = new Image();
        img.onload = function() {
            const canvas = document.createElement('canvas');
            const MAX_SIZE = 500;
            let width = img.width;
            let height = img.height;
            if (width > height) {
                if (width > MAX_SIZE) {
                    height = Math.round(height * (MAX_SIZE / width));
                    width = MAX_SIZE;
                }
            } else {
                if (height > MAX_SIZE) {
                    width = Math.round(width * (MAX_SIZE / height));
                    height = MAX_SIZE;
                }
            }
            canvas.width = width;
            canvas.height = height;
            const ctx = canvas.getContext('2d');
            ctx.drawImage(img, 0, 0, width, height);
            const dataUrl = canvas.toDataURL('image/jpeg', 0.75);

            const hiddenInput = document.getElementById('editImageBase64');
            const previewDiv = document.getElementById('editImagePreview');
            const urlInput = document.getElementById('editImageUrl');
            if (hiddenInput) hiddenInput.value = dataUrl;
            if (urlInput) urlInput.value = '';
            if (previewDiv) {
                previewDiv.innerHTML = `<img src="${dataUrl}" style="width:100%;height:100%;object-fit:cover;" onerror="this.parentElement.innerHTML='📦'"/>`;
            }
        };
        img.src = e.target.result;
    };
    reader.readAsDataURL(file);
}

function previewUrlImage(event) {
    const url = event.target.value.trim();
    const hiddenInput = document.getElementById('editImageBase64');
    const previewDiv = document.getElementById('editImagePreview');
    const fileInput = document.getElementById('editImageFile');
    if (hiddenInput) hiddenInput.value = url;
    if (fileInput && url) fileInput.value = '';
    if (previewDiv) {
        if (url) {
            previewDiv.innerHTML = `<img src="${url}" style="width:100%;height:100%;object-fit:cover;" onerror="this.parentElement.innerHTML='📦'"/>`;
        } else {
            previewDiv.innerHTML = '📦';
        }
    }
}

async function submitEditProduct(event, oldName, id) {
    event.preventDefault();
    try {
        showLoading();
        const newName = document.getElementById('editNameInput')?.value.trim() || oldName;
        const newQty = parseFloat(document.getElementById('editQtyInput')?.value || 0);
        const newPrice = parseFloat(document.getElementById('editPriceInput')?.value || 0);
        const newSupplier = document.getElementById('editSupplierInput')?.value.trim() || '';
        const newImg = document.getElementById('editImageBase64')?.value || '';

        if (getProductsAPI()) {
            await getProductsAPI().updateProduct(oldName, id, {
                name: newName,
                quantity: newQty,
                unit_price: newPrice,
                supplier_name: newSupplier,
                image_url: newImg
            });
        }
        closeCustomModal();
        showToast(t('recordAdded'), 'success');
        await loadProductsData();
    } catch (err) {
        // silent
    } finally {
        hideLoading();
    }
}

function openDeleteModal(name, id) {
    const box = document.getElementById('customModalBox');
    const overlay = document.getElementById('customModalOverlay');
    if (!box || !overlay) return;
    box.innerHTML = `
        <h3 class="modal-title" style="color:var(--danger);">🗑️ ${t('deleteProductTitle')}</h3>
        <p class="modal-body" style="margin-top:0.75rem;">${t('confirmDeleteMsg')}<br><strong>${escapeHtml(name)}</strong></p>
        <div class="modal-actions">
            <button type="button" class="btn btn-outline" onclick="closeCustomModal()">${t('cancel')}</button>
            <button type="button" class="btn btn-danger" onclick="submitDeleteProduct('${escapeHtml(name).replace(/'/g, "\\'")}', '${id || ''}')">🗑️ ${t('deleteBtn')}</button>
        </div>
    `;
    overlay.classList.add('active');
}

async function submitDeleteProduct(name, id) {
    try {
        showLoading();
        if (getProductsAPI()) await getProductsAPI().deleteProduct(name, id);
        closeCustomModal();
        showToast(t('recordAdded'), 'success');
        await loadProductsData();
    } catch (err) {
        // silent
    } finally {
        hideLoading();
    }
}

function closeCustomModal() {
    const overlay = document.getElementById('customModalOverlay');
    if (overlay) overlay.classList.remove('active');
}

// ============================================================
// OPERATIONS HISTORY
// ============================================================

function renderOperationsPage() {
    return `
        <div class="table-container">
            <div class="table-header">
                <h3 class="table-title">📋 ${t('operations')}</h3>
                <div class="table-filters">
                    <input type="text" class="form-input" id="opsSearch" placeholder="${t('search')}" oninput="filterOperationsTable()">
                    <input type="date" class="form-input" id="opsDateFilter" onchange="filterOperationsTable()">
                    <select class="form-select" id="opsEmployeeFilter" onchange="filterOperationsTable()">
                        <option value="">${t('filterByEmployee')}</option>
                        ${EMPLOYEES.map(emp => `<option value="${emp.ar}">${t(emp.en) || emp.ar}</option>`).join('')}
                    </select>
                    <select class="form-select" id="opsTypeFilter" onchange="filterOperationsTable()">
                        <option value="all">${t('all')}</option>
                        <option value="in">📥 ${t('in')}</option>
                        <option value="out">📤 ${t('out')}</option>
                    </select>
                </div>
            </div>
            <div class="table-wrap">
                <table>
                    <thead>
                        <tr>
                            <th>${t('type')}</th>
                            <th>${t('productName')}</th>
                            <th>${t('quantity')}</th>
                            <th>${t('unitPrice')} / ${t('totalPrice')}</th>
                            <th>${t('supplierName')} / ${t('customerName')}</th>
                            <th>${t('date')}</th>
                            <th>${t('employeeName')}</th>
                            <th>PDF</th>
                        </tr>
                    </thead>
                    <tbody id="operationsTableBody">
                        <tr><td colspan="8" class="empty-state"><p>${t('loading')}</p></td></tr>
                    </tbody>
                </table>
            </div>
        </div>
    `;
}

async function loadOperationsData() {
    try {
        showLoading();
        const [inRecords, outRecords] = await Promise.all([
            getInventoryInAPI() ? getInventoryInAPI().getAll() : [],
            getInventoryOutAPI() ? getInventoryOutAPI().getAll() : []
        ]);
        AppState.inventoryIn = inRecords;
        AppState.inventoryOut = outRecords;
        renderOperationsTable();
    } catch (err) {
        // Silent fail
    } finally {
        hideLoading();
    }
}

function getAllOperations() {
    return [
        ...AppState.inventoryIn.map(r => ({ ...r, opType: 'in', contactField: r.supplier_name, dateField: r.entry_date, priceField: r.unit_price })),
        ...AppState.inventoryOut.map(r => ({ ...r, opType: 'out', contactField: r.customer_name, dateField: r.date, priceField: r.total_selling_price }))
    ].sort((a, b) => new Date(b.created_at) - new Date(a.created_at));
}

function renderOperationsTable(ops = null) {
    const tbody = document.getElementById('operationsTableBody');
    if (!tbody) return;
    const operations = ops || getAllOperations();
    if (operations.length === 0) {
        tbody.innerHTML = `<tr><td colspan="8" class="empty-state"><div class="empty-icon">📋</div><p>${t('noOperations')}</p></td></tr>`;
        return;
    }
    tbody.innerHTML = operations.map(op => `
        <tr>
            <td><span class="badge ${op.opType === 'in' ? 'badge-in' : 'badge-out'}">${op.opType === 'in' ? '📥 ' + t('in') : '📤 ' + t('out')}</span></td>
            <td><strong>${escapeHtml(op.product_name)}</strong></td>
            <td>${formatNumber(op.quantity)}</td>
            <td>${op.opType === 'in' ? formatCurrency(op.priceField) + ' / ' + formatCurrency(op.total_price) : formatCurrency(op.total_selling_price)}</td>
            <td>${escapeHtml(op.contactField || '-')}</td>
            <td>${formatDate(op.dateField)}</td>
            <td>${escapeHtml(op.employee_name || '-')}</td>
            <td>
                <button class="btn btn-sm btn-outline" onclick="downloadOperationPDF('${op.id}', '${op.opType}')" title="${t('downloadPDF')}">
                    📄 PDF
                </button>
            </td>
        </tr>
    `).join('');
}

function filterOperationsTable() {
    const searchQuery = (document.getElementById('opsSearch')?.value || '').toLowerCase();
    const dateFilter = document.getElementById('opsDateFilter')?.value || '';
    const employeeFilter = (document.getElementById('opsEmployeeFilter')?.value || '').toLowerCase();
    const typeFilter = document.getElementById('opsTypeFilter')?.value || 'all';
    let ops = getAllOperations();
    if (searchQuery) ops = ops.filter(op => op.product_name.toLowerCase().includes(searchQuery) || (op.contactField && op.contactField.toLowerCase().includes(searchQuery)));
    if (dateFilter) ops = ops.filter(op => (op.dateField || '').split('T')[0] === dateFilter);
    if (employeeFilter) ops = ops.filter(op => op.employee_name && op.employee_name.toLowerCase().includes(employeeFilter));
    if (typeFilter !== 'all') ops = ops.filter(op => op.opType === typeFilter);
    renderOperationsTable(ops);
}

// ============================================================
// PDF DOWNLOAD
// ============================================================

async function downloadOperationPDF(id, opType) {
    try {
        showLoading();
        let record;
        if (opType === 'in') {
            record = getInventoryInAPI() ? await getInventoryInAPI().getById(id) : null;
            if (record && getPDFGenerator()) await getPDFGenerator().generateInventoryInPDF(record, translations[AppState.currentLang]);
        } else {
            record = getInventoryOutAPI() ? await getInventoryOutAPI().getById(id) : null;
            if (record && getPDFGenerator()) await getPDFGenerator().generateInventoryOutPDF(record, translations[AppState.currentLang]);
        }
        if (!record) { hideLoading(); return; }
    } catch (err) {
        // Silent fail
    } finally {
        hideLoading();
    }
}

// ============================================================
// INITIALIZATION
// ============================================================

function initApp() {
    const savedLang = localStorage.getItem('kaizen_lang') || 'en';
    switchLanguage(savedLang);
    document.querySelectorAll('.sidebar-nav a').forEach(link => {
        link.addEventListener('click', (e) => {
            e.preventDefault();
            const page = link.dataset.page;
            if (page) navigateTo(page);
        });
    });
    document.getElementById('sidebarOverlay')?.addEventListener('click', closeSidebar);
    document.getElementById('customModalOverlay')?.addEventListener('click', (e) => {
        if (e.target.id === 'customModalOverlay') closeCustomModal();
    });
    if (window.initializeDatabase) window.initializeDatabase();
    renderPage('dashboard');
}

document.addEventListener('DOMContentLoaded', initApp);
