/**
 * pdf.js - PDF Export Module
 * Kaizen Inventory Management System
 * Uses jsPDF library loaded via CDN.
 */

var PDFGenerator = window.PDFGenerator = {
    async generateInventoryInPDF(record, translations) {
        const { jsPDF } = window.jspdf;
        const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
        const t = translations;
        const pageWidth = 210, margin = 15;
        let y = margin;

        // Header
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(22);
        doc.setTextColor(30, 58, 138);
        doc.text('KAIZEN', pageWidth / 2, y, { align: 'center' });
        y += 8;
        doc.setFontSize(10);
        doc.setTextColor(100, 100, 100);
        doc.text(t.inventoryManagementSystem || 'Inventory Management System', pageWidth / 2, y, { align: 'center' });
        y += 5;
        doc.setDrawColor(30, 58, 138);
        doc.setLineWidth(0.5);
        doc.line(margin, y, pageWidth - margin, y);

        // Transaction type
        y += 10;
        doc.setFontSize(16);
        doc.setTextColor(22, 163, 74);
        doc.setFont('helvetica', 'bold');
        doc.text(t.inventoryInReceipt || 'INVENTORY IN - RECEIPT', pageWidth / 2, y, { align: 'center' });

        // Info box
        y += 8;
        doc.setDrawColor(220, 220, 220);
        doc.setFillColor(248, 250, 252);
        doc.roundedRect(margin, y, pageWidth - margin * 2, 8, 2, 2, 'F');
        doc.setFontSize(9);
        doc.setTextColor(80, 80, 80);
        doc.setFont('helvetica', 'normal');
        const dateStr = record.created_at ? new Date(record.created_at).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }) : '-';
        doc.text(`${t.date || 'Date'}: ${dateStr}`, margin + 3, y + 5.5);
        doc.text(`${t.receiptNo || 'Receipt No'}: ${record.id ? record.id.slice(0, 8).toUpperCase() : '-'}`, pageWidth / 2, y + 5.5);
        doc.text(`${t.entryDate || 'Entry Date'}: ${record.entry_date || '-'}`, pageWidth - margin - 3, y + 5.5, { align: 'right' });

        // Details
        y += 16;
        doc.setFontSize(12);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(30, 58, 138);
        doc.text(t.transactionDetails || 'Transaction Details', margin, y);
        y += 7;

        const details = [
            { label: t.productName || 'Product Name', value: record.product_name || '-' },
            { label: t.quantity || 'Quantity', value: record.quantity || '-' },
            { label: t.unitPrice || 'Unit Price', value: record.unit_price ? `${parseFloat(record.unit_price).toFixed(2)} ${t.currencySymbol || 'EGP'}` : '-' },
            { label: t.totalPrice || 'Total Price', value: record.total_price ? `${parseFloat(record.total_price).toFixed(2)} ${t.currencySymbol || 'EGP'}` : '-' },
            { label: t.supplierName || 'Supplier Name', value: record.supplier_name || '-' },
            { label: t.employeeName || 'Employee Name', value: record.employee_name || '-' },
            { label: t.notes || 'Notes', value: record.notes || '-' }
        ];

        details.forEach(detail => {
            doc.setFillColor(245, 247, 250);
            doc.roundedRect(margin, y, pageWidth - margin * 2, 7, 1, 1, 'F');
            doc.setFontSize(9);
            doc.setFont('helvetica', 'bold');
            doc.setTextColor(60, 60, 60);
            doc.text(detail.label + ':', margin + 3, y + 4.5);
            doc.setFont('helvetica', 'normal');
            doc.setTextColor(40, 40, 40);
            doc.text(detail.value, margin + 55, y + 4.5);
            y += 8;
        });

        // Footer
        y += 10;
        doc.setDrawColor(200, 200, 200);
        doc.line(margin, y, pageWidth - margin, y);
        y += 5;
        doc.setFontSize(7);
        doc.setTextColor(150, 150, 150);
        doc.setFont('helvetica', 'normal');
        doc.text(t.generatedByKaizen || 'Generated by Kaizen Inventory Management System', pageWidth / 2, y, { align: 'center' });
        y += 4;
        doc.text(`${t.generatedOn || 'Generated on'}: ${new Date().toLocaleString()}`, pageWidth / 2, y, { align: 'center' });

        doc.save(`Kaizen_InventoryIn_${record.id ? record.id.slice(0, 8) : 'receipt'}.pdf`);
    },

    async generateInventoryOutPDF(record, translations) {
        const { jsPDF } = window.jspdf;
        const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
        const t = translations;
        const pageWidth = 210, margin = 15;
        let y = margin;

        // Header
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(22);
        doc.setTextColor(30, 58, 138);
        doc.text('KAIZEN', pageWidth / 2, y, { align: 'center' });
        y += 8;
        doc.setFontSize(10);
        doc.setTextColor(100, 100, 100);
        doc.text(t.inventoryManagementSystem || 'Inventory Management System', pageWidth / 2, y, { align: 'center' });
        y += 5;
        doc.setDrawColor(30, 58, 138);
        doc.setLineWidth(0.5);
        doc.line(margin, y, pageWidth - margin, y);

        // Transaction type
        y += 10;
        doc.setFontSize(16);
        doc.setTextColor(220, 38, 38);
        doc.setFont('helvetica', 'bold');
        doc.text(t.inventoryOutReceipt || 'INVENTORY OUT - ISSUE SLIP', pageWidth / 2, y, { align: 'center' });

        // Info box
        y += 8;
        doc.setDrawColor(220, 220, 220);
        doc.setFillColor(248, 250, 252);
        doc.roundedRect(margin, y, pageWidth - margin * 2, 8, 2, 2, 'F');
        doc.setFontSize(9);
        doc.setTextColor(80, 80, 80);
        doc.setFont('helvetica', 'normal');
        const dateStr = record.created_at ? new Date(record.created_at).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }) : '-';
        doc.text(`${t.date || 'Date'}: ${dateStr}`, margin + 3, y + 5.5);
        doc.text(`${t.issueNo || 'Issue No'}: ${record.id ? record.id.slice(0, 8).toUpperCase() : '-'}`, pageWidth / 2, y + 5.5);
        doc.text(`${t.issueDate || 'Issue Date'}: ${record.date || '-'}`, pageWidth - margin - 3, y + 5.5, { align: 'right' });

        // Details
        y += 16;
        doc.setFontSize(12);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(30, 58, 138);
        doc.text(t.transactionDetails || 'Transaction Details', margin, y);
        y += 7;

        const details = [
            { label: t.productName || 'Product Name', value: record.product_name || '-' },
            { label: t.quantity || 'Quantity', value: record.quantity || '-' },
            { label: t.totalSellingPrice || 'Total Selling Price', value: record.total_selling_price ? `${parseFloat(record.total_selling_price).toFixed(2)} ${t.currencySymbol || 'EGP'}` : '-' },
            { label: t.customerName || 'Customer Name', value: record.customer_name || '-' },
            { label: t.employeeName || 'Employee/Seller Name', value: record.employee_name || '-' },
            { label: t.notes || 'Notes', value: record.notes || '-' }
        ];

        details.forEach(detail => {
            doc.setFillColor(245, 247, 250);
            doc.roundedRect(margin, y, pageWidth - margin * 2, 7, 1, 1, 'F');
            doc.setFontSize(9);
            doc.setFont('helvetica', 'bold');
            doc.setTextColor(60, 60, 60);
            doc.text(detail.label + ':', margin + 3, y + 4.5);
            doc.setFont('helvetica', 'normal');
            doc.setTextColor(40, 40, 40);
            doc.text(detail.value, margin + 55, y + 4.5);
            y += 8;
        });

        // Footer
        y += 10;
        doc.setDrawColor(200, 200, 200);
        doc.line(margin, y, pageWidth - margin, y);
        y += 5;
        doc.setFontSize(7);
        doc.setTextColor(150, 150, 150);
        doc.setFont('helvetica', 'normal');
        doc.text(t.generatedByKaizen || 'Generated by Kaizen Inventory Management System', pageWidth / 2, y, { align: 'center' });
        y += 4;
        doc.text(`${t.generatedOn || 'Generated on'}: ${new Date().toLocaleString()}`, pageWidth / 2, y, { align: 'center' });

        doc.save(`Kaizen_InventoryOut_${record.id ? record.id.slice(0, 8) : 'issue'}.pdf`);
    }
};
